<html><head><script type="text/javascript">var _sf_startpt=(new Date()).getTime()
</script><title>Unhandled Promise Rejections in Node.js | www.thecodebarbarian.com</title><meta name="viewport" content="width=device-width, initial-scale=1"/><link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css"/><link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600" rel="stylesheet" type="text/css"/><link href="//fonts.googleapis.com/css?family=Merriweather:400,400italic,600,700" rel="stylesheet" type="text/css"/><link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/><link href="/style/style.css" rel="stylesheet" type="text/css"/><link href="/style/github.css" rel="stylesheet" type="text/css"/><script href="http://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script><script href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script><script href="/javascript/sidebar.js" type="text/javascript"></script><meta property="og:title" content="Unhandled Promise Rejections in Node.js"/><meta property="og:url" content="http://www.thecodebarbarian.com/unhandled-promise-rejections-in-node.js"/><meta property="og:image" content="http://i.imgur.com/AefJJ21.png"/><meta property="og:site_name" content="The Code Barbarian"/></head><body><div class="navbar social-links hidden-sm hidden-xs"><div class="container"><ul class="nav navbar-nav navbar-right"><li><a href="http://www.twitter.com/code_barbarian">twitter</a></li><li><a href="http://www.github.com/vkarpov15">github</a></li><li><a href="http://thecodebarbarian.com/feed.xml">rss</a></li></ul></div></div><div id="nav" class="navbar"><div class="container"><div class="navbar-header"><a href="http://thecodebarbarian.com" class="navbar-brand big-brand"><img src="/images/Barbarian_Head.png" class="logo"/><span class="site-name">The Code Barbarian</span></a></div><div id="home-nav-mobile" class="navbar-right collapse navbar-collapse"><ul class="nav navbar-nav"><li><a href="http://thecodebarbarian.com/tag/mongodb.html">MongoDB</a></li><li><a href="http://thecodebarbarian.com/tag/angularjs.html">AngularJS</a></li><li><a href="http://thecodebarbarian.com/tag/nodejs.html">NodeJS</a></li><li><a href="http://thecodebarbarian.com/tag/paleo.html">Paleo</a></li><li class="hidden-md hidden-lg"><a href="#">@code_barbarian</a></li><li class="hidden-md hidden-lg"><a href="#">TCB Github</a></li><li class="hidden-md hidden-lg"><a href="#">TCB Facebook</a></li></ul></div></div></div><div class="container-fluid"><div id="desktop-right-bar" class="col-lg-3 col-lg-offset-9 right-bar"><div class="right-bar-content-slider pull-right"><div class="row search-container"><div class="col-lg-12"><div class="form-group"></div><label>Search</label><form onsubmit="window.location.href = 'https://www.google.im/search?q=' + encodeURIComponent(document.getElementById('searchQ').value) + '+site:thecodebarbarian.com'; return false;"><div class="input-group"><input id="searchQ" type="text" class="form-control"/><div class="input-group-addon search-button"><i class="fa fa-search"></i></div></div></form></div></div><div class="row recent-posts right-bar-group"><div class="col-lg-12 books"><div><a href="http://es2015generators.com"><img src="https://i.imgur.com/xvGNKlr.png"/></a></div><div><script type="text/javascript" src="//cdn.carbonads.com/carbon.js?zoneid=1673&amp;serve=C6AILKT&amp;placement=thecodebarbariancom" id="_carbonads_js"></script></div></div></div><div class="row recent-posts right-bar-group"><div class="col-lg-12"><p class="right-bar-label">Most Popular</p><ul class="list-unstyled"><li class="right-bar-li"><a href="http://thecodebarbarian.com/common-async-await-design-patterns-in-node.js.html">Common Async/Await Design Patterns in Node.js</a></li><li class="right-bar-li"><a href="http://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html">Unhandled Promise Rejections in Node.js</a></li><li class="right-bar-li"><a href="http://thecodebarbarian.com/80-20-guide-to-async-await-in-node.js.html">The 80/20 Guide to Async/Await in Node.js</a></li><li class="right-bar-li"><a href="http://thecodebarbarian.com/getting-started-with-webassembly-in-node.js.html">Getting Started With WebAssembly in Node.js</a></li><li class="right-bar-li"><a href="http://thecodebarbarian.com/2015/01/24/angularjs-interceptors.html">An 80/20 Guide to AngularJS HTTP Interceptors</a></li></ul></div></div></div></div></div><div id="mobile-sharing-options" class="container-fluid hidden-sm hidden-md hidden-lg"><div class="row"><div class="col-lg-12"><div class="post-sharing-options"><div class="row"><div class="col-xs-3 twitter-share sharing-option"><a href="https://twitter.com/share?url=http%3A%2F%2Fwww.thecodebarbarian.com%2Funhandled-promise-rejections-in-node.js&amp;via=code_barbarian" class="social"><i class="fa fa-twitter"></i></a></div><div class="col-xs-3 facebook-share sharing-option"><a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.thecodebarbarian.com%2F%2Funhandled-promise-rejections-in-node.js" class="social"><i class="fa fa-facebook"></i></a></div><div class="col-xs-3 google-share sharing-option"><a href="https://plus.google.com/share?url=http%3A%2F%2Fwww.thecodebarbarian.com%2F%2Funhandled-promise-rejections-in-node.js" class="social"><i class="fa fa-google-plus"></i></a></div><div class="col-xs-3 comment sharing-option"><a href="#disqus_thread" class="social"><i class="fa fa-comment"></i></a></div></div></div></div></div></div><div id="desktop-sharing-options" class="post-sharing-options hidden-xs pull-left"><ul class="list-unstyled"><li class="twitter-share"><a href="https://twitter.com/share?url=http%3A%2F%2Fwww.thecodebarbarian.com%2Funhandled-promise-rejections-in-node.js&amp;via=code_barbarian" class="social"><i class="fa fa-twitter sharing-option"></i></a></li><li class="facebook-share"><a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.thecodebarbarian.com%2F%2Funhandled-promise-rejections-in-node.js" class="social"><i class="fa fa-facebook sharing-option"></i></a></li><li class="google-share"><a href="https://plus.google.com/share?url=http%3A%2F%2Fwww.thecodebarbarian.com%2F%2Funhandled-promise-rejections-in-node.js" class="social"><i class="fa fa-google-plus sharing-option"></i></a></li></ul></div><div class="container"><div class="col-lg-9 post-text"><div class="row"><div class="title-byline-container"><h1 class="post-title">Unhandled Promise Rejections in Node.js </h1><div class="credits"><span class="byline">by Valeri Karpov</span><span class="byhandle"><a href="http://www.twitter.com/code_barbarian">@code_barbarian</a></span><span class="bydate">April 04, 2017</span></div></div></div><div class="post-body-text-container"><p>Node.js 6.6.0 added a sporadically useful bug/feature: <a href="https://nodejs.org/api/process.html#process_event_rejectionhandled">logging unhandled promise rejections to the console by default</a>. In other words, the below script will print an error to the console:</p>
<pre><code class="lang-javascript"><span class="hljs-built_in">Promise</span>.reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'woops'</span>));

<span class="hljs-comment">/* Output:
$ node test.js
(node:7741) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: woops
(node:7741) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */</span>
</code></pre>
<p><a href="http://bluebirdjs.com/docs/api/suppressunhandledrejections.html">Bluebird has supported similar behavior for quite a while</a>. I&#39;ve <a href="https://github.com/nodejs/node/issues/830#issuecomment-254904199">vocally expressed my distaste for this behavior in the past</a>, it&#39;s actually one of the many reasons why I don&#39;t use bluebird. But now that this behavior is in core node, it appears we&#39;re all stuck with it, so we better learn to take advantage of it.</p>
<h2 id="what-is-an-unhandled-rejection-">What is an Unhandled Rejection?</h2>
<p>&quot;Rejection&quot; is the canonical term for a promise reporting an error. As defined in ES6, a promise is a state machine representation of an asynchronous operation and <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise">can be in one of 3 states</a>: &quot;pending&quot;, &quot;fulfilled&quot;, or &quot;rejected&quot;. A pending promise represents an asynchronous operation that&#39;s in progress and a fulfilled promise represents an asynchronous operation that&#39;s completed successfully. A rejected promise represents an asynchronous operation that failed for some reason. For example, trying to connect to a nonexistent MongoDB instance using the MongoDB driver will give you a promise rejection:</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">const</span> { MongoClient } = <span class="hljs-built_in">require</span>(<span class="hljs-string">'mongodb'</span>);

MongoClient.connect(<span class="hljs-string">'mongodb://notadomain'</span>);

<span class="hljs-comment">/* Output:
$ node test.js
(node:9563) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [notadomain:27017] on first connect [MongoError: getaddrinfo ENOTFOUND notadomain notadomain:27017]
(node:9563) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */</span>
</code></pre>
<p>Recall that the ES6 style promise constructor takes an &quot;executor&quot; function that takes 2 functions as arguments, <code>resolve</code> and <code>reject</code>. One way to cause a promise rejection is to call <code>reject()</code>:</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((resolve, reject) =&gt; {
  setTimeout(() =&gt; reject(<span class="hljs-string">'woops'</span>), <span class="hljs-number">500</span>);
});

<span class="hljs-comment">/* Output:
$ node test.js
(node:8128) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): woops
(node:8128) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */</span>
</code></pre>
<p>Another way is to throw an exception in the executor function:</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>(() =&gt; { <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'exception!'</span>); });

<span class="hljs-comment">/* Output
$ node test.js
(node:8383) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: exception!
(node:8383) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */</span>
</code></pre>
<p>Some argue that <a href="http://2ality.com/2016/03/promise-rejections-vs-exceptions.html">throwing an exception in the executor function is bad practice</a>. I strongly disagree. Consolidated error handling is a strong design pattern, and going back to the days where we had to wrap async function calls in <code>try/catch</code> as well as handle the callback <code>error</code> param is a step in the wrong direction.</p>
<p><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Chaining">Chaining</a> is how you handle promise rejections. ES6 promises have a handy <code>.catch()</code> helper function for handling rejections.</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'woops'</span>))).
  <span class="hljs-comment">// Prints "caught woops"</span>
  <span class="hljs-keyword">catch</span>(error =&gt; { <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'caught'</span>, error.message); });

<span class="hljs-comment">// Equivalent. `.catch(fn)` is essentially identical to `.then(null, fn)`</span>
<span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'woops'</span>))).
  <span class="hljs-comment">// Prints "caught woops"</span>
  then(<span class="hljs-literal">null</span>, error =&gt; { <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'caught'</span>, error.message); });
</code></pre>
<p>Seems easy, right? How about the below code, what will it print?</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'woops'</span>))).
  <span class="hljs-keyword">catch</span>(error =&gt; { <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'caught'</span>, err.message); });
</code></pre>
<p>It&#39;ll print out an unhandled rejection warning. Notice that <code>err</code> is not defined!</p>
<pre><code>$ node test.js
(node:<span class="hljs-number">9825</span>) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: <span class="hljs-number">2</span>): <span class="hljs-built_in">ReferenceError</span>: err is not defined
(node:<span class="hljs-number">9825</span>) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process <span class="hljs-keyword">with</span> a non-zero exit code.
</code></pre><p>This is why unhandled rejections can be so insidious. You might think you caught an error, but your error handler might have caused another error. You get a similar problem if you return a promise in your <code>.catch()</code> function. For example, let&#39;s say you use an <a href="https://docs.sentry.io/clients/node/">misconfigured sentry client</a> for logging errors and return a promise representing tracking the error to sentry.</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">const</span> sentry = <span class="hljs-built_in">require</span>(<span class="hljs-string">'raven'</span>);

<span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'woops'</span>))).
  <span class="hljs-keyword">catch</span>(error =&gt; <span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((resolve, reject) =&gt; {
    sentry.captureMessage(error.message, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">error</span>) </span>{
      <span class="hljs-keyword">if</span> (error) {
        <span class="hljs-keyword">return</span> reject(error);
      }
      resolve();
    });
  }));

<span class="hljs-comment">/* Output
$ node test.js
(node:10019) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'user' of undefined
(node:10019) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
*/</span>
</code></pre>
<p>There are a lot of nasty gotchas with unhandled rejections. That&#39;s why Node.js gives you a mechanism for globally handling unhandled rejections.</p>
<h2 id="the-unhandledrejection-event">The <code>unhandledRejection</code> Event</h2>
<p>The node <code>process</code> global has <a href="https://nodejs.org/api/process.html#process_event_unhandledrejection">an <code>unhandledRejection</code> event</a> for unhandled promise rejection. Note that this <strong>only</strong> works for native promises, so if you do something like <code>global.Promise = require(&#39;bluebird&#39;)</code> the below code won&#39;t work. Your event handler will receive the promise rejection error as its first parameter:</p>
<pre><code class="lang-javascript">process.on(<span class="hljs-string">'unhandledRejection'</span>, error =&gt; {
  <span class="hljs-comment">// Will print "unhandledRejection err is not defined"</span>
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'unhandledRejection'</span>, error.message);
});

<span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'woops'</span>))).
  <span class="hljs-keyword">catch</span>(error =&gt; {
    <span class="hljs-comment">// Will not execute</span>
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'caught'</span>, err.message);
  });
</code></pre>
<p>Note that, while the <code>error</code> parameter to the &#39;unhandledRejection&#39; event should be a JavaScript error, it doesn&#39;t necessarily have to be. Calling <code>reject()</code> with a non-error is <a href="http://eslint.org/docs/rules/prefer-promise-reject-errors">considered bad practice</a>, but if you do, &#39;unhandledRejection&#39; will get the argument you passed to <code>reject()</code>.</p>
<pre><code class="lang-javascript">process.on(<span class="hljs-string">'unhandledRejection'</span>, error =&gt; {
  <span class="hljs-comment">// Prints "unhandledRejection woops!"</span>
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'unhandledRejection'</span>, error.test);
});

<span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject({ test: <span class="hljs-string">'woops!'</span> }));
</code></pre>
<p>Note that if you attach a listener to &#39;unhandledRejection&#39;, the default warning to the console (the <code>UnhandledPromiseRejectionWarning</code> from previous examples) will <strong>not</strong> print to the console. That message <strong>only</strong> gets printed if you don&#39;t have a handler for &#39;unhandledRejection&#39;.</p>
<p>If you want to suppress the unhandled promise rejection warning, all you need to do is call <code>.catch()</code> on the promise with an empty function.</p>
<pre><code class="lang-javascript">process.on(<span class="hljs-string">'unhandledRejection'</span>, error =&gt; {
  <span class="hljs-comment">// Won't execute</span>
  <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'unhandledRejection'</span>, error.test);
});

<span class="hljs-keyword">new</span> <span class="hljs-built_in">Promise</span>((_, reject) =&gt; reject({ test: <span class="hljs-string">'woops!'</span> })).catch(() =&gt; {});
</code></pre>
<p>This is how you suppress unhandled rejection handling when you&#39;re absolutely sure you don&#39;t want to handle the error. Why would you want to suppress unhandled rejection handling? Let&#39;s say you used <a href="https://www.npmjs.com/package/sinon">sinon</a> to stub out a function that returns a promise in a <a href="https://www.npmjs.com/package/mocha">mocha</a> <code>before()</code> test hook. The below test succeeds:</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">const</span> sinon = <span class="hljs-built_in">require</span>(<span class="hljs-string">'sinon'</span>);

<span class="hljs-keyword">const</span> obj = {
  fn: () =&gt; {}
};

before(<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>) </span>{
  sinon.stub(obj, <span class="hljs-string">'fn'</span>).returns(<span class="hljs-built_in">Promise</span>.resolve());
});

it(<span class="hljs-string">'works'</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-keyword">return</span> obj.fn();
});
</code></pre>
<p>However, what if you want to stub out <code>obj.fn()</code> to return a promise that rejects? The below script will log an unhandled rejection warning:</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">const</span> assert = <span class="hljs-built_in">require</span>(<span class="hljs-string">'assert'</span>);
<span class="hljs-keyword">const</span> sinon = <span class="hljs-built_in">require</span>(<span class="hljs-string">'sinon'</span>);

<span class="hljs-keyword">const</span> obj = {
  fn: () =&gt; {}
};

before(<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>) </span>{
  sinon.stub(obj, <span class="hljs-string">'fn'</span>).returns(<span class="hljs-built_in">Promise</span>.reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'test'</span>)));
});

it(<span class="hljs-string">'works'</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-keyword">return</span> obj.fn().catch(error =&gt; {
    assert.equal(error.message, <span class="hljs-string">'test'</span>);
  });
});
</code></pre>
<p>This is where &#39;unhandledRejection&#39; starts breaking down the abstraction barriers of promises. Now, <code>.catch()</code> is no longer a pure function and has global side effects. For example, one way to avoid the unhandled rejection warning above is to call <code>.catch()</code> on the promise but not use the promise that <code>.catch()</code> returns:</p>
<pre><code class="lang-javascript">before(<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-keyword">const</span> p = <span class="hljs-built_in">Promise</span>.reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'test'</span>));
  p.catch(() =&gt; {});
  <span class="hljs-comment">// No more warning! `.catch()` mutates `p`'s internal state.</span>
  sinon.stub(obj, <span class="hljs-string">'fn'</span>).returns(p);
});
</code></pre>
<h2 id="implications-for-async-await">Implications for Async/Await</h2>
<p><a href="http://thecodebarbarian.com/80-20-guide-to-async-await-in-node.js.html">Async/await</a> has a major advantage over building promise chains manually: <code>await</code> handles <code>.catch()</code> for you. For example:</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">async</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">test</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-comment">// No unhandled rejection!</span>
  <span class="hljs-keyword">await</span> <span class="hljs-built_in">Promise</span>.reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'test'</span>));
}

test().catch(() =&gt; {});
</code></pre>
<p>However, notice the <code>.catch()</code> call chained onto <code>test()</code>. Remember that an <code>async</code> function returns a promise! No <code>.catch()</code> there will give you an unhandled rejection.</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">async</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">test</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-comment">// No unhandled rejection!</span>
  <span class="hljs-keyword">await</span> <span class="hljs-built_in">Promise</span>.reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'test'</span>));
}

test();

<span class="hljs-comment">/* Output:
$ node test.js
(node:13912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: test
(node:13912) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */</span>
</code></pre>
<p>Async/await lets you construct promises that represent complex operations involving loops, conditionals, etc., but in the end you still get a promise back. Remember to handle your errors!</p>
<p>In case you were wondering, you <strong>cannot</strong> make <code>async</code> functions return a non-native promise. So there&#39;s no way to make a promise library that bypasses node&#39;s unhandled rejection handler and integrates with async/await.</p>
<pre><code class="lang-javascript">global.Promise = <span class="hljs-built_in">require</span>(<span class="hljs-string">'bluebird'</span>);

<span class="hljs-keyword">async</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">test</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-comment">// No unhandled rejection!</span>
  <span class="hljs-keyword">await</span> <span class="hljs-built_in">Promise</span>.reject(<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'test'</span>));
}

<span class="hljs-comment">// Prints "false"</span>
<span class="hljs-built_in">console</span>.log(test().catch(() =&gt; {}) <span class="hljs-keyword">instanceof</span> <span class="hljs-built_in">require</span>(<span class="hljs-string">'bluebird'</span>));
</code></pre>
<p><em>You might not be able to plug custom promise libraries into async/await, but you can into the ES6 equivalent, <a href="https://www.npmjs.com/package/co">co</a>. Check out <a href="http://es2015generators.com/">my ebook on ES6 generators</a> to learn how to write your own co from scratch and master the fundamental underpinnings of async/await.</em></p>
</div><div style="color: #666666; border-top: 1px dashed #666666; margin: 25px; text-align: center; padding-top: 10px"><em>Found a typo or error? Open up a pull request! This post is
available as markdown on&nbsp;<a href="https://github.com/vkarpov15/thecodebarbarian.com/blob/master/lib/posts/20170404_unhandled_rejections.md">Github</a></em></div><div id="disqus_thread"></div><script type="text/javascript">/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'codebarbarian'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();</script><noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript><a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a></div></div><div style="padding-bottom: 100px">&nbsp;</div><script type="text/javascript">!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
  analytics.load("5DErrxzVhprg8sNh8xaiKDR6dNa7yGTI");
  analytics.page()
}}();</script><script type="text/javascript">analytics.track('opened post',
  { title: "Unhandled Promise Rejections in Node.js", time: new Date() });
  </script></body></html>